modLoader="javafml"
loaderVersion="[38,)"
issueTrackerURL="https://github.com/Mrbysco/Dimensional-Paintings/issues"
license="MIT"

[[mods]]
modId="dimpaintings"
version="${file.jarVersion}"
displayName="Dimensional Paintings"
displayURL="https://www.curseforge.com/minecraft/mc-mods/dimensional-paintings"
authors="Mrbysco, ShyNieke"
description='''
Just jump in :)
'''
[[dependencies.dimpaintings]]
modId="minecraft"
mandatory=true
versionRange="[1.18,1.19)"
ordering="NONE"
side="BOTH"